### ISSUE TITLE
should we move this to the broccolijs org?

### ISSUE THREAD

**Issue by stefanpenner** [broccolijs/broccoli-test-helper#3]
thoughts @rwjblue ?

**Comment by rwjblue** [comment]
Yes, but we should also fix the broccoli-test-helpers vs broccoli-test-helper issue. 😩

**Comment by stefanpenner** [comment]
I think we should just cut over to this library it works much better.

**Comment by rwjblue** [comment]
Yep, we should only have one, but I think we offer multiple "test helpers" here and I am always typing `yarn add broccoli-test-helpers` instead of `yarn add broccoli-test-helper` accidentally.  

I _think_ the better long term name is `broccoli-test-helpers`?

**Comment by krisselden** [comment]
I don't have any opinions on the name, I didn't think too much about it. I think it would be good to move.

**Comment by krisselden** [comment]
any more thoughts?

**Comment by stefanpenner** [comment]
nope. would love to move it. but only you can ;)
